name: nightly

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
  workflow_dispatch:
  schedule:
    - cron: '18 */6 * * *'

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 15
    steps:
      - uses: actions/checkout@v3
        with:
          name: woodpecker-ci/woodpecker
          ref: refs/heads/master
      - uses: actions/setup-node@v3
        with:
          node-version: '16.x'
      - uses: actions/setup-go@v3
        with:
          go-version: '1.18.x'
      - run: |
          pwd
          ls

          echo '>>> BUILDING WEB'
          pushd web
          yarn install --frozen-lockfile
          yarn build
          popd

          echo '>>> BUILDING ALL'
          go mod vendor
          make release-server
          make release-agent
          make release-cli

          echo '>>> DONE'
          find dist
      - uses: actions/upload-artifact@v3
        with:
          name: artifact
          path: dist
